apiVersion: v1
kind: Service
metadata:
  name: {{ include "exam.fullname" . }}
  labels:
    {{- include "exam.labels" . | nindent 4 }}
spec:
  type: {{ .Values.flower.service.type }}
  ports:
    - port: {{ .Values.flower.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: flower
    {{- include "exam.selectorLabels" . | nindent 4 }}
