apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "exam.fullname" . }}-producer
  labels:
    {{- include "exam.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: producer
        {{- include "exam.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.producer.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "exam.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.producer.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.producer.securityContext | nindent 12 }}
          image: "{{ .Values.producer.image.repository }}:{{ .Values.producer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.producer.image.pullPolicy }}
          command:
          - python
          - producer.py
          resources:
            {{- toYaml .Values.producer.resources | nindent 12 }}
          env:
            - name: TASK_MIN_DURATION
              value: {{ .Values.producer.task_duration.min | default 10 | quote }}
            - name: TASK_MAX_DURATION
              value: {{ .Values.producer.task_duration.max | default 40 | quote }}
            - name: TASK_STEP_DURATION
              value: {{ .Values.producer.task_duration.step | default 2 | quote }}
            - name: BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: '{{ template "exam.fullname" . }}-env'
                  key: BROKER_URL
      {{- with .Values.producer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.producer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.producer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
