name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "master", "main" ]
    paths: ["exercise-2/**"]

  push:
    branches: [ "master", "main" ]
    paths: ["exercise-2/**"]


jobs:
  linter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: exercise-2
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: |
            requirements/base.txt
            requirements/local.txt

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  pytest:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Build the Stack
        run:  docker-compose build

      - name: Run DB Migrations
        run:  docker-compose run --rm django python manage.py migrate

      - name: Run Django Tests
        run:  docker-compose run django pytest

      - name: Tear down the Stack
        run:  docker-compose down
