apiVersion: v1
kind: Service
metadata:
  name: {{ template "exam.fullname" . }}-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: {{ include "exam.name" . }}
    app.kubernetes.io/name: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
