apiVersion: v1
kind: Secret
metadata:
  name: '{{ template "exam.fullname" . }}-env'
  labels:
    app: {{ template "exam.fullname" . }}
    chart: {{ template "exam.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  BROKER_URL: "redis://:{{ tpl .Values.connections.redis_password . }}@{{ tpl .Values.connections.redis_host . }}:{{ .Values.connections.redis_port | default "6379" }}/{{ tpl .Values.connections.redis_database . }}"